require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.0

Metrics/LineLength:
  Max: 135

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/berta/cli.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
