require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 135

Metrics/MethodLength:
  Max: 15
  Exclude:
   - 'lib/berta/cli.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'
Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/berta/cli.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
