sudo: false

language: ruby
rvm:
    - ruby-head
    - 2.3.4
    - 2.2.7
    - 2.1.10

matrix:
    allow_failures:
        - rvm: ruby-head
        - rvm: 2.1.10
fast_finish: true

branches:
    only:
        - master

before_install: 'gem install bundler -v 1.13.0'

script: 'bundle exec rake acceptance'
