berta:
  opennebula:
    secret:                        # Secret for OpenNebula authentication
    endpoint:                      # OpenNebula backend endpoint
  expiration:                      # Action that will be set for execution
    offset: 10 days                # Time until action will be executed
    action: terminate-hard         # Type of action that will be executed
  notification:
    deadline: 1 day                # Time when user should be notified before action will be executed
  filter:                          # Filter VMs in after fetch
    type: exclude                  # Type of filter, options are include and exclude
    ids:                           # VMs with this IDs will be used in filter
    users:                         # VMs owned by this users will be used in filter
    groups:                        # VMs in this groups will be used in filter
    clusters:                      # VMs in this clusters will be used in filter
  logging:
    file: /var/log/berta/berta.log # File to write log to. To turn off file logging leave this field empty
    level: error                   # Logging level
  dry-run: false                   # Berta won't change anything on running instance of OpenNebula
  debug: false                     # Debug mode
