berta:
  action: # Action that will be set for execution
    offset: 864000 # Time until action will be executed
    type: suspend # Type of action that will be executed
  notification:
    time: 86400 # Time when user should be notified before action will be executed
