berta:
  opennebula:
    secret:
    url:
  expiration: # Action that will be set for execution
    offset: 864000 # Time until action will be executed
    action: suspend # Type of action that will be executed
  notification:
    deadline: 86400 # Time when user should be notified before action will be executed
  whitelist:
    id:
    user:
    group:
    cluster:
